#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

echo '
-------------------------------------
            ██╗  ██╗██████╗
            ██║  ██║╚════██╗
            ███████║ █████╔╝
            ╚════██║██╔═══╝
                 ██║███████╗
                 ╚═╝╚══════╝
                       Algoritmos

Author: Ivan Lopes
  Mail: lopesivan.ufrj@gmail.com
  Site: ivanlopes.eng.br

Brought to you by ivanlopes.eng.br
-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------
"
chown abc:abc /app
chown abc:abc /config
chown abc:abc /defaults

. /usr/local/bin/entrypoint.sh
